In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
from sklearn.datasets import load_diabetes

In [10]:
diabetes = load_diabetes()

In [11]:
diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [12]:
diabetes.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [13]:
diabetes.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [16]:
diabetes.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [19]:
data = pd.DataFrame(diabetes.data,columns=diabetes.feature_names)

In [20]:
data

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [21]:
data.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019907 -0.017646  
1 -0.039493 -0.068332 -0.092204  
2 -0.002592  0.002861 -0.025930  
3  0.034309  0.022688 -0.009362  
4 -0.002592 -0.031988 -0.046641

In [22]:
data.tail()

age       sex       bmi        bp        s1        s2        s3  \
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064

In [23]:
# To add target

data['target'] = diabetes.target

In [24]:
data

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  target  
0   -0.002592  0.019907 -0.017646   151.0  
1   -0.039493 -0.068332 -0.092204    75.0  
2   -0.002592  0.002861 -0.025930   141.0  
3    0.034309  0.022688 -0.009362   206.0  
4   -0.002592 -0.031988 -0.046641   135.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018114  0.044485   104.0  
439 -0.011080 -0.046883  0.015491   132.0  
440  0.026560  0.044529 -0.025930   220.0  
441 -0.039493 -0.004222  0.003064    57.0  

[442 rows x 11 columns]

In [26]:
# EDA and Data preparation

x = data.drop('target',axis = 1)
y = data['target']

In [27]:
x

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [28]:
y

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...  
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: target, Length: 442, dtype: float64

In [29]:
# split the data into train and test

from sklearn.model_selection import train_test_split


In [31]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [32]:
x_train

age       sex       bmi        bp        s1        s2        s3  \
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
232  0.012648  0.050680  0.000261 -0.011420  0.039710  0.057245 -0.039719   
80   0.070769 -0.044642  0.012117  0.042529  0.071357  0.053487  0.052322   
46  -0.056370 -0.044642 -0.011595 -0.033213 -0.046975 -0.047660  0.004460   
381 -0.070900  0.050680 -0.089197 -0.074527 -0.042848 -0.025739 -0.032356   
..        ...       ...       ...       ...       ...       ...       ...   
255  0.001751 -0.044642 -0.065486 -0.005670 -0.007073 -0.019476  0.041277   
72   0.063504  0.050680 -0.004050 -0.012556  0.103003  0.048790  0.056003   
396 -0.085430  0.050680 -0.030996 -0.022885 -0.063487 -0.054236  0.019187   
235  0.067136  0.050680 -0.014828  0.058608 -0.059359 -0.034508 -0.061809   
37  -0.009147 -0.044642  0.011039 -0.057313 -0.024960 -0.042963  0.030232   

           s4        s5        s6  
438  0.034309 -0.018114  0.044485  
232  0.056081  0.024055  0.032059  
80  -0.002592  0.025395 -0.005220  
46  -0.039493 -0.007977 -0.088062  
381 -0.002592 -0.012909 -0.054925  
..        ...       ...       ...  
255 -0.039493 -0.003301  0.007207  
72  -0.002592  0.084492 -0.017646  
396 -0.039493 -0.096435 -0.034215  
235  0.012906 -0.005142  0.048628  
37  -0.039493  0.017036 -0.005220  

[353 rows x 10 columns]

In [33]:
x_test

age       sex       bmi        bp        s1        s2        s3  \
246  0.041708 -0.044642 -0.032073 -0.061892  0.079612  0.050982  0.056003   
425 -0.078165 -0.044642 -0.040696 -0.081413 -0.100638 -0.112795  0.022869   
293 -0.070900 -0.044642  0.092953  0.012680  0.020446  0.042527  0.000779   
31  -0.023677 -0.044642 -0.065486 -0.081413 -0.038720 -0.053610  0.059685   
359  0.038076  0.050680  0.005650  0.032201  0.006687  0.017475 -0.024993   
..        ...       ...       ...       ...       ...       ...       ...   
277 -0.034575 -0.044642 -0.059019  0.001215 -0.053855 -0.078035  0.067048   
132  0.016281  0.050680 -0.021295 -0.009113  0.034206  0.047850  0.000779   
213  0.001751 -0.044642 -0.070875 -0.022885 -0.001569 -0.001001  0.026550   
286 -0.038207 -0.044642 -0.054707 -0.077970 -0.033216 -0.086490  0.140681   
256 -0.049105 -0.044642  0.160855 -0.046985 -0.029088 -0.019790 -0.047082   

           s4        s5        s6  
246 -0.009972  0.045067 -0.059067  
425 -0.076395 -0.020292 -0.050783  
293  0.000360 -0.054540 -0.001078  
31  -0.076395 -0.037129 -0.042499  
359  0.034309  0.014821  0.061054  
..        ...       ...       ...  
277 -0.076395 -0.021395  0.015491  
132 -0.002592 -0.012909  0.023775  
213 -0.039493 -0.022517  0.007207  
286 -0.076395 -0.019198 -0.005220  
256  0.034309  0.028020  0.011349  

[89 rows x 10 columns]

In [35]:
y_train

438    104.0
232    259.0
80     143.0
46     190.0
381    104.0
       ...  
255    153.0
72     202.0
396     43.0
235    124.0
37     276.0
Name: target, Length: 353, dtype: float64

In [36]:
y_test

246     78.0
425    152.0
293    200.0
31      59.0
359    311.0
       ...  
277     64.0
132    107.0
213     49.0
286     60.0
256    346.0
Name: target, Length: 89, dtype: float64

In [37]:
x_train.shape,x_test.shape

((353, 10), (89, 10))

In [ ]:
# scaling (optional)

In [38]:
# model training

from sklearn.linear_model import LinearRegression

In [39]:
model =  LinearRegression()

In [40]:
model

LinearRegression()

In [42]:
model.fit(x_train,y_train)

LinearRegression()

In [44]:
model.coef_

array([ -30.62219046, -272.2506057 ,  528.85252681,  327.69716891,
       -581.01973841,  332.97061365,  -27.97314298,  139.28036115,
        665.07667773,   61.90517166])

In [46]:
model.intercept_

np.float64(151.4300932966009)

In [47]:
# interpretation
# say age has coef value -30.62219046
# interpretation > 1 unit change in age then target value decreases by -30 units on an average
# other feature /factors are kept constant


x_train

age       sex       bmi        bp        s1        s2        s3  \
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
232  0.012648  0.050680  0.000261 -0.011420  0.039710  0.057245 -0.039719   
80   0.070769 -0.044642  0.012117  0.042529  0.071357  0.053487  0.052322   
46  -0.056370 -0.044642 -0.011595 -0.033213 -0.046975 -0.047660  0.004460   
381 -0.070900  0.050680 -0.089197 -0.074527 -0.042848 -0.025739 -0.032356   
..        ...       ...       ...       ...       ...       ...       ...   
255  0.001751 -0.044642 -0.065486 -0.005670 -0.007073 -0.019476  0.041277   
72   0.063504  0.050680 -0.004050 -0.012556  0.103003  0.048790  0.056003   
396 -0.085430  0.050680 -0.030996 -0.022885 -0.063487 -0.054236  0.019187   
235  0.067136  0.050680 -0.014828  0.058608 -0.059359 -0.034508 -0.061809   
37  -0.009147 -0.044642  0.011039 -0.057313 -0.024960 -0.042963  0.030232   

           s4        s5        s6  
438  0.034309 -0.018114  0.044485  
232  0.056081  0.024055  0.032059  
80  -0.002592  0.025395 -0.005220  
46  -0.039493 -0.007977 -0.088062  
381 -0.002592 -0.012909 -0.054925  
..        ...       ...       ...  
255 -0.039493 -0.003301  0.007207  
72  -0.002592  0.084492 -0.017646  
396 -0.039493 -0.096435 -0.034215  
235  0.012906 -0.005142  0.048628  
37  -0.039493  0.017036 -0.005220  

[353 rows x 10 columns]

In [48]:
# prediction

y_pred = model.predict(x_test)

In [50]:
y_pred

array([119.14235853, 110.77183282, 185.03750644,  68.00997114,
       171.05444208, 190.41916188, 218.59009744, 119.63375975,
       157.26867822, 129.50082172, 214.15123432, 202.9228174 ,
        88.41924038,  71.96523457, 236.88645879, 206.09667095,
       175.60536299, 101.96502781, 114.10950995, 169.04562492,
       187.71464103,  85.64466706, 144.1354953 , 107.06903899,
        94.04844034, 211.79832988,  90.72839769, 176.23084464,
       122.62288816, 180.92495472, 157.11598543, 138.04315918,
       192.36322448,  94.45469648, 166.30860041, 189.43644667,
       110.67690284, 247.6779722 , 172.47370249, 188.08959083,
       160.08451415, 176.65318031, 115.81198266, 120.23187992,
       141.5360933 , 203.4072105 , 152.43166715, 144.09802539,
       190.18999626, 191.4950697 ,  59.81227803, 159.75688911,
       102.14767931, 147.89042458, 186.10407036, 121.41211882,
       159.12303468,  83.43835172,  55.57818196,  79.08303804,
        99.4572998 , 199.89514677, 168.54643127, 109.16

In [51]:
# performance metrics

from sklearn.metrics import mean_squared_error,r2_score

In [52]:
 mean_squared_error(y_test,y_pred)

2992.5812293010176

In [53]:
r2_score(y_test,y_pred)

0.4384316213369278